spring.application.name=armyBuilderV2
spring.datasource.url=jdbc:postgresql://localhost:5432/builder
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.jpa.hibernate.ddl-auto=create